FROM debian:trixie-slim AS chef
ARG FDB_VERSION_RANGE="7.4"
RUN curl -fLs 'https://api.github.com/repos/apple/foundationdb/releases?per_page=100' | \
    jq --arg RANGE "${FDB_VERSION_RANGE}" -r '[.[] | select(.tag_name | startswith($RANGE + "."))]'

FROM chef AS planner
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
RUN cargo chef cook --release --recipe-path recipe.json
RUN cargo build -p stalwart --no-default-features --features "foundationdb s3 redis azure nats enterprise" --release
